 management:
 security:
  enabled: true
  roles: SUPERUSER
 context-path: /manage
security:
 basic:
  enabled: true
  path: /manage
 user:
  name: admin
  password: adminaccess
  
logging:
 level:
  org.springframework.web: INFO
 pattern:
  file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
 
application:
 common:
  
server:
 tomcat:
  accesslog:
   directory: /opt/artdotcom/${spring.application.name}/log
   enabled: true

