management:
 security:
  enabled: true
  
logging:
 level:
  org.springframework.web: INFO
 pattern:
  file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
 
application:
 common:
  
server:
 tomcat:
  accesslog:
   directory: /opt/artdotcom/${spring.application.name}/log
   enabled: true

env:
 cache:
  redis:
   url: 'dev-redis.art.com:18143,password=devappaccess'
   hostname: dev-redis.art.com
   port: 18143
   password: '{cipher}eaebe5f67f3b70d0688a83308ff677104f8a22c59ac80951105c4d04db6d4d16'
   timeout: 300
   
 db:
 
  connectionStrings:
   map:
    dTrack : 'Data Source=SAC-DBDEV01.art.com;Initial Catalog=dTrack;Integrated Security=False;User ID=devapp;Password=devappaccess;" providerName="System.Data.SqlClient"' 
    dSite_lite : 'Data Source=SAC-DBDEV01.art.com;Initial Catalog=dsite_lite;Integrated Security=False;User ID=devapp;Password=devappaccess;" providerName="System.Data.SqlClient'
    dCart : 'Data Source=SAC-DBDEV01.art.com;Initial Catalog=dCart;Integrated Security=False;User ID=devapp;Password=devappaccess;" providerName="System.Data.SqlClient'
 
  sqlServerConfig:
   dBuilderMaster: 
    user: devapp
    password: '{cipher}eaebe5f67f3b70d0688a83308ff677104f8a22c59ac80951105c4d04db6d4d16'
    server: sac-dbdev02.art.com
    port: 1433
    database: dBuilder_Master

   dSiteLite: 
    user: devapp
    password: '{cipher}eaebe5f67f3b70d0688a83308ff677104f8a22c59ac80951105c4d04db6d4d16'
    server: SAC-DBDEV01.art.com
    url: 'Data Source=SAC-DBDEV01.art.com;Initial Catalog=dsite_lite;Integrated Security=False;User ID=devapp;Password=devappaccess;" providerName="System.Data.SqlClient'
    dbDriver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    port: 1433
    database: dSiteLite
    connectionTimeOut: 60000
    maxPoolSize: 300
    idleTimeout: 30000
 
   dTrack: 
    user: devapp
    password: '{cipher}eaebe5f67f3b70d0688a83308ff677104f8a22c59ac80951105c4d04db6d4d16'
    server: SAC-DBDEV01.art.com
    url: jdbc:sqlserver://SAC-DBDEV01.art.com;databaseName=dTrack
    dbDriver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    port: 1433
    database: dSiteLite
